services:
  db:
    image: mysql:8.0
    container_name: oliveb2b-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  wordpress:
    image: wordpress:latest
    container_name: oliveb2b-wp
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - wp_core:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "${WP_PORT}:80"

  wpcli:
    image: wordpress:cli
    container_name: oliveb2b-wpcli
    depends_on:
      - db
      - wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    volumes:
      - wp_core:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./docker/wpcli-init.sh:/usr/local/bin/wpcli-init.sh:ro
    entrypoint: ["/bin/sh", "/usr/local/bin/wpcli-init.sh"]

volumes:
  db_data:
  wp_core:
